blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/your-org/llm-hub/tree/main/docs
    about: Check our comprehensive documentation for guides and references
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/your-org/llm-hub/blob/main/docs/TROUBLESHOOTING.md
    about: Common issues and solutions for LLM Hub
  - name: 🚀 Quick Start Guide
    url: https://github.com/your-org/llm-hub/blob/main/docs/INSTALL.md
    about: Step-by-step installation and setup instructions
  - name: 🔒 Security Issues
    url: https://github.com/your-org/llm-hub/blob/main/SECURITY.md
    about: Report security vulnerabilities privately (do not create public issues)
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/llm-hub/discussions
    about: Ask questions and discuss ideas with the community
